// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0pMBmhSWmMm_VmOjBk3pgonhhMJZLEUE',
    appId: '1:800472186443:web:1ff9a75305e33514f4d7ce',
    messagingSenderId: '800472186443',
    projectId: 'todoapp-a6b36',
    authDomain: 'todoapp-a6b36.firebaseapp.com',
    storageBucket: 'todoapp-a6b36.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIoqbVBisDN5IeWbox4Smy91mZZRkh8YQ',
    appId: '1:800472186443:android:e85690605090e276f4d7ce',
    messagingSenderId: '800472186443',
    projectId: 'todoapp-a6b36',
    storageBucket: 'todoapp-a6b36.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9K4hZ89TIMNZks-iRZKJ-sU8cv04GBdE',
    appId: '1:800472186443:ios:1211b810ba86e3e5f4d7ce',
    messagingSenderId: '800472186443',
    projectId: 'todoapp-a6b36',
    storageBucket: 'todoapp-a6b36.firebasestorage.app',
    iosBundleId: 'com.example.toDoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9K4hZ89TIMNZks-iRZKJ-sU8cv04GBdE',
    appId: '1:800472186443:ios:1211b810ba86e3e5f4d7ce',
    messagingSenderId: '800472186443',
    projectId: 'todoapp-a6b36',
    storageBucket: 'todoapp-a6b36.firebasestorage.app',
    iosBundleId: 'com.example.toDoApp',
  );
}
